import { Button, HStack, Select, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { getAllGuides } from '../lib/api'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const allGuidesData = await getAllGuides([
    'slug',
    'action',
    'object',
    'location',
  ])

  return {
    props: {
      allGuidesData,
    }
  }
}

export default function Home({ allGuidesData }) {

  // record user choice
  const [path, setPath] = useState({});
  const router = useRouter();

  async function handleClick() {
    // console.log(JSON.stringify(path, null, 2));
    console.log(path);

    if (path?.action === undefined
      || path?.object === undefined
      || path?.location === undefined) {
      return;
    }

    router.push(`/guides/${path.action}-${path.object}-${path.location}`)

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>slyde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/*
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        */}

        {/* Begin custom additions */}

        <p className={styles.description}>
          I want to...
        </p>
        <VStack spacing={4}>

          <HStack>
            <Select
              placeholder='Action'
              onChange={e => { path.action = e.currentTarget.value; setPath(path) }}>
              <option value='send'>Send</option>
              <option value='buy'>Buy</option>
            </Select>
            <Select
              placeholder='Object'
              onChange={e => { path.object = e.currentTarget.value; setPath(path) }}>
              <option value='eth'>ETH</option>
              <option value='matic'>MATIC</option>
            </Select>
            <p>to</p>
            <Select
              placeholder='Location'
              onChange={e => { path.location = e.currentTarget.value; setPath(path) }}>
              <option value='polygon'>Polygon Address</option>
              <option value='ethereum'>ETH Address</option>
            </Select>
          </HStack>

          <Button onClick={handleClick}>
            Go &rarr;
          </Button>
        </VStack>

        {/*
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
         </div>
         */}
      </main>

      <footer className={styles.footer}>
        <p>slyde</p>
      </footer>
    </div>
  )
}
