import { Button, HStack, Select, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { getAllGuides } from '../lib/api'
import styles from '../styles/Home.module.css'
import {Provider, NETWORKS} from '@web3-ui/core'
import { ConnectWallet, useWallet } from '@web3-ui/core';


export async function getStaticProps() {
  const allGuidesData = await getAllGuides([
    'slug',
    'action',
    'object',
    'location',
  ])

  return {
    props: {
      allGuidesData,
    }
  }
}

export default function Home({ allGuidesData }) {

  // record user choice
  const [path, setPath] = useState({});
  const router = useRouter();

  async function handleClick() {
    // console.log(JSON.stringify(path, null, 2));
    console.log(path);

    if (path?.action === undefined
      || path?.object === undefined
      || path?.location === undefined) {
      return;
    }

    router.push(`/guides/${path.action}-${path.object}-${path.location}`)

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>slyde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <p className={styles.description}>
          I want to...
        </p>
        <VStack spacing={4}>

          <HStack>
            <Select
              placeholder='Action'
              onChange={e => { path.action = e.currentTarget.value; setPath(path) }}>
              <option value='send'>Send</option>
              <option value='buy'>Buy</option>
            </Select>
            <Select
              placeholder='Object'
              onChange={e => { path.object = e.currentTarget.value; setPath(path) }}>
              <option value='eth'>ETH</option>
              <option value='matic'>MATIC</option>
            </Select>
            <p>to</p>
            <Select
              placeholder='Location'
              onChange={e => { path.location = e.currentTarget.value; setPath(path) }}>
              <option value='polygon'>Polygon Address</option>
              <option value='ethereum'>ETH Address</option>
            </Select>
          </HStack>

          <Button onClick={handleClick}>
            Go &rarr;
          </Button>
        </VStack>

      </main>

      <footer className={styles.footer}>
        <p>slyde</p>
      </footer>
    </div>
  )
}
